services:
  - type: web
    name: imsucopias-telegram-bot
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m modules.dept_02_comercio_ventas.telegram_voice_bot
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0