services:
  - type: worker
    name: imsucopias-telegram-bot
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_bots.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0